kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: docker-exe
  image: plugins/docker
  settings:
    registry: host.docker.internal:5000
    target: compile
    repo: host.docker.internal:5000/zugai-exe
    tags: latest
    cache-from:
    - host.docker.internal:5000/zugai-exe:latest
- name: docker-bot
  image: plugins/docker
  settings:
    registry: host.docker.internal:5000
    target: bot
    repo: host.docker.internal:5000/zugai-bot
    tags: latest
    cache-from:
    - host.docker.internal:5000/zugai-exe:latest
    - host.docker.internal:5000/zugai-bot:latest
- name: webhook-bot
  image: plugins/webhook
  settings:
    urls:
      from_secret: bot_webhook_url
- name: docker-web
  image: plugins/docker
  settings:
    registry: host.docker.internal:5000
    target: web
    repo: host.docker.internal:5000/zugai-web
    tags: latest
    cache-from:
    - host.docker.internal:5000/zugai-exe:latest
    - host.docker.internal:5000/zugai-web:latest
- name: webhook-web
  image: plugins/webhook
  settings:
    urls:
      from_secret: web_webhook_url
