name:                zugai
version:             0.1.0.0
github:              "toaq/zugai"
license:             BSD3
author:              "The Toaq Coders"
maintainer:          "lynn@foldr.moe"
copyright:           "2022 The Toaq Coders"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A library/program for parsing and interpreting Toaq Gamma text.

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.12
- containers >= 0.6
- microaeson >= 0.1.0.1
- parsec >= 3.1.14.0
- pretty-simple
- split >= 0.2.3.4
- text >= 2.0
- bytestring-trie >= 0.2.7
- unicode-transforms >= 0.4.0.1

library:
  source-dirs: src
  default-extensions:
    DeriveFunctor
    ImportQualifiedPost
    OverloadedStrings

executables:
  zugai-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zugai

tests:
  zugai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
      OverloadedStrings
    dependencies:
    - zugai
    - hspec
